Observatorio/Django-env/src/ProjectObservatorio/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import  path,include
from django.conf.urls.static import static  
from django.conf.urls import url


from posts import views
from portal import views
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('portal.urls', 'portal'), namespace='portal')),
    path('accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Observatorio/Django-env/src/portal/urls.py
from django.urls import include, path

from portal import views

urlpatterns = [
    path('',views.inicio, name='inicio'),    
    path('contact',views.contacto, name='contact'),
    path('invite',views.invitacionAdmin, name='inviteadmin'),      
    path('solicitud_registro',views.solicitud_registro, name='solicitudregistro'),      

]

Observatorio/Django-env/src/posts/urls.py
from django.urls import include, path

from posts import views

urlpatterns = [
    path('',views.post_list, name='list'),
    path('news_list',views.post_list_update, name='newslistupdate'),
    path('create/',views.post_create, name='create'),
    path('<slug:slug>/',views.post_detail, name='detail'),
    path('edit/<int:id>',views.post_update, name="update"),
    # path('<slug:slug>/delete/',views.post_delete, name='delete'),
    path('delete/<int:id>',views.post_delete, name='delete'),

]

Observatorio/Django-env/src/users/urls.py
from django.urls import include, path

from users import views

urlpatterns = [
    path('list_user',views.user_list, name='userlist'),     
    path('detail_user',views.user_detail, name='userdetail'),     
    path('update_user',views.user_update, name='userupdate'),     
    path('enable_admin_user',views.user_enable_admin, name='userenableadmin'),     
    path('<int:id>',views.user_enable_detail, name='userenabledetail'),     
    path('admin/<int:id>',views.user_enable_detail_admin, name='userenabledetailadmin'),     
    path('update_user_list',views.user_list_update, name='userlistupdate'),     
    path('update_user_observatorio/<int:id>',views.user_update_observatorio, name='userupdateobservatorio'), 
    path('update_user_observatorio/admin/<int:id>',views.user_Admin_update_observatorio, name='useradminupdateobservatorio'), 
    path('user_list_disable_admin',views.user_list_disable_admin, name='userlistdisableadmin'),     
    path('user_list_disable_egresado',views.user_list_disable_egresado, name='userlistdisableegresado'),     
    path('disable_user/<int:id>',views.user_disable, name='userdisable'),    
    path('disable_user/admin/<int:id>',views.user_admin_disable, name='useradmindisable'),    
    path('enable_egresado_user',views.user_enable_egresado, name='userenableegresado'),
]

Observatorio/Django-env/src/posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
# Create your models here.

class PostManager(models.Manager):
    def active(self,*args,**kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte= timezone.now())


def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

class Post (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE) 
    titulo = models.CharField(max_length= 150)
    slug = models.SlugField(unique= True)
    imagen = models.ImageField(upload_to=upload_location,
        null = True,
        blank = True,
        height_field="height_field", 
        width_field="width_field")
    height_field=models.IntegerField(default=0)
    width_field=models.IntegerField(default=0)
    contenido=models.TextField()
    draft = models.BooleanField(default= False)
    publish = models.DateField(auto_now_add=False , auto_now = False)
    timestamp = models.DateTimeField(auto_now_add=True , auto_now = False)
    actualizado= models.DateTimeField(auto_now_add=False , auto_now = True)

    objects = PostManager()

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={"slug":self.slug}) #namespace posts
        #"/posts/%s/" %(self.id)
    
    class Meta:
        ordering = ["-timestamp","actualizado"]

def create_slug(instance, new_slug= None):
    slug = slugify(instance.titulo)
    if new_slug is not None:
        slug = new_slug
    queryset = Post.objects.filter(slug= slug).order_by("-id")
    exists = queryset.exists()
    if exists:
        new_slug="%s-%s" %(slug, queryset.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)
#class Intereses 

Observatorio/Django-env/src/posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        
        fields ={
            "titulo",
            "contenido",
            "imagen",
            "draft",
            "publish"
        }
class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        
        fields ={
            "titulo",
            "contenido",
            "imagen",
            "draft",
            "publish"
        }

Observatorio/Django-env/src/posts/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import Paginator
from django.contrib.auth import authenticate
from django.utils import timezone
from django.db.models import Q
from django.core.exceptions import PermissionDenied
# Create your views here.

from .forms import PostForm ,PostUpdateForm
from .models import Post #importo mi modelo


def post_create(request):
    if not request.user.Administrador :
        print("Bienvenido %s" %(request.user))
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    #if request.method == "POST":
    #print (request.POST.get("titulo"))
    if form.is_valid():
        instance = form.save(commit = False)
        #print( form.cleaned_data.get("titulo"))
        instance.user = request.user
        instance.save()
        messages.success(request, "tu Noticia ha sido creado con exito")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {        
        "form": form,
    }
    if request.user.Administrador:
        return render(request,"post_form.html", context)
    else:
        raise PermissionDenied

def post_detail(request, slug=None):
    #instance= Post.objects.get(id=None)
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.Administrador:
            raise Http404    
    share_string = quote_plus(instance.titulo)
    context = {        
        "title": instance.titulo,
        "instance": instance,
        "share_string":share_string,
    }
    if request.user.Administrador or request.user.Egresado:
        return render(request,"post_detail.html", context)
    else:
        raise PermissionDenied
    

def post_list(request):
    hoy = timezone.now().date()
    queryset = Post.objects.active()#filter(draft=False).filter(publish__lte= timezone.now())#all(),order_by("-timestamp")
    if request.user.Administrador and not request.user.is_superuser:
        queryset = Post.objects.all()
    query = request.GET.get("q")
    if query:
        queryset=queryset.filter(
            Q(titulo__icontains=query)|
            Q(contenido__icontains=query)|
            Q(user__first_name__icontains=query)
            ).distinct()
    paginator = Paginator(queryset, 2) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    objects_list = paginator.get_page(page_number)
    
    context = {
        "objects_list": objects_list,
        "title": "Listado Noticias", 
        "hoy": hoy,        
    }

    if request.user.Administrador or request.user.Egresado:
        return render(request,"post_list.html", context)
    else:
        raise PermissionDenied


def post_list_update(request):
    hoy = timezone.now().date()
    queryset = Post.objects.active()#filter(draft=False).filter(publish__lte= timezone.now())#all(),order_by("-timestamp")
    if request.user.Administrador and not request.user.is_superuser:
        queryset = Post.objects.filter(user=request.user)
    query = request.GET.get("q")
    if query:
        queryset=queryset.filter(
            Q(titulo__icontains=query)|
            Q(contenido__icontains=query)|
            Q(user__first_name__icontains=query)
            ).distinct()
    paginator = Paginator(queryset, 2) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    objects_list = paginator.get_page(page_number)
    
    context = {
        "objects_list": objects_list,
        "title": "Listado Noticias", 
        "hoy": hoy,        
    }

    if request.user.Administrador:
        return render(request,"post_list_update.html", context)
    else:
        raise PermissionDenied

def post_update(request, id= None):
    Bandequery= 0
    if not request.user.Administrador :
        raise Http404
    instance = get_object_or_404(Post, id=id) 

    if request.user == instance.user:
        Bandequery= 1

    if Bandequery== 1:
        form = PostUpdateForm(request.POST or None, request.FILES or None, instance= instance)# edit el form
        if form.is_valid():
            instance = form.save(commit = False)
            instance.save()
            messages.success(request, "Tu Noticia ha sido modificada", extra_tags="html_safe")                
            return HttpResponseRedirect(instance.get_absolute_url())    

        context = {        
            "title": instance.titulo,
            "instance": instance,
            "form": form,
        }

    if Bandequery== 1:
        if request.user.Administrador:
            return render(request,"post_form_update.html", context)
        else:
            raise PermissionDenied
    else:
        raise PermissionDenied

def post_delete(request, id=None):
    Bandequery= 0
    if not request.user.Administrador:
        raise Http404
    instance = get_object_or_404(Post, id=id)

    if request.user == instance.user:
        Bandequery= 1

    if Bandequery== 1:
        instance.delete()
        messages.success(request, "tu post ha sido Eliminado")

    if Bandequery== 1:
        if request.user.Administrador:
            return redirect("posts:list")
        else:
            raise PermissionDenied
    else:
        raise PermissionDenied
    
# def post_update(request, slug= None):
#     if not request.user.Administrador :
#         raise Http404
#     instance = get_object_or_404(Post, slug=slug) 

#     form = PostForm(request.POST or None, request.FILES or None, instance= instance)# edit el form
#     if form.is_valid():
#         instance = form.save(commit = False)
#         instance.save()
#         messages.success(request, "tu <a href='#'> post </a> ha sido modificado", extra_tags="html_safe")                
#         return HttpResponseRedirect(instance.get_absolute_url())    

#     context = {        
#         "title": instance.titulo,
#         "instance": instance,
#         "form": form,
#     }
#     if request.user.Administrador:
#         return render(request,"post_form.html", context)
#     else:
#         raise PermissionDenied

Observatorio/Django-env/src/templates/contacto.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}Contacto | {{block.super}}{% endblock %}

{% block content %}

    <div class="col-sm-10 col-sm-offset-1">
        {% if titulo %}
        <!-- <h1 class="text-align-center"><strong>{{ titulo }}</strong></h1> -->
        {% endif %}
        
        <form method="POST" action="{% url 'portal:contact' %}">{% csrf_token %}
            {{ form_contacto|crispy }}
            <b></b>
            <p class="text-center"><input class="btn btn-primary" type="submit" value="Enviar"/>
            <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a> </p>
        </form>
    </div>

{% endblock %}

Observatorio/Django-env/src/templates/headsidebar.html
{% load static %}

<br>
<br>
<div class="bg-light border-right" id="sidebar-wrapper" > <!-- id="page-content-wrapper" -->
    <div class="page-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-4" id="right">
                        <div class="panel panel-default ">
                            <div class="panel-heading">
                                <h3 class="panel-title"><strong>Opciones</strong></h3>
                            </div>
                            <!--User details -->
                            <div class="bg-light border-right" id="sidebar-wrapper" class="panel-body">

                                {% if not user.is_superuser and request.user.Administrador %}
                                <a href="{% url 'posts:create' %}" class="list-group-item list-group-item-action bg-light">Crear Noticia</a>
                                <a href="{% url 'posts:newslistupdate' %}" class="list-group-item list-group-item-action bg-light">Modificar Noticia</a>
                                <a href="{% url 'posts:list' %}" class="list-group-item list-group-item-action bg-light">Ver Noticias</a>
                                <a href="{% url 'users:userenableegresado' %}" class="list-group-item list-group-item-action bg-light">Habilitar Cuenta Egresado</a>
                                <a href="{% url 'users:userlistupdate' %}"class="list-group-item list-group-item-action bg-light" >Modificar Cuenta Egresado</a>
                                <a href="{% url 'users:userlistdisableegresado' %}"class="list-group-item list-group-item-action bg-light">Deshabilitar Cuenta Egresado</a>
                                <a href="{% url 'users:userlist' %}" class="list-group-item list-group-item-action bg-light">Buscar Cuenta Egresado</a>
                                <a href="#"class="list-group-item list-group-item-action bg-light">Crear Interes</a>
                                <a href="{% url 'users:userupdate' %}" class="list-group-item list-group-item-action bg-light">Editar Perfil</a>
                                <a href="{% url 'auth_password_change' %}" class="list-group-item list-group-item-action bg-light">Modificar Contraseña</a>
                                {% endif %}

                                {% if  user.is_superuser %}
                                <a href="{% url 'portal:inviteadmin' %}" class="list-group-item list-group-item-action bg-light">Invitar Administrador</a>
                                <a href="{% url 'users:userenableadmin' %}" class="list-group-item list-group-item-action bg-light">Habilitar Cuenta Administrador</a>
                                <a href="{% url 'users:userlistupdate' %}" class="list-group-item list-group-item-action bg-light">Modificar Cuenta Administrador</a>
                                <a href="{% url 'users:userlistdisableadmin' %}" class="list-group-item list-group-item-action bg-light">Deshabilitar Cuenta Administrador</a>
                                <a href="{% url 'users:userlist' %}" class="list-group-item list-group-item-action bg-light">Buscar Cuenta Administrador</a>
                                <a href="{% url 'users:userupdate' %}" class="list-group-item list-group-item-action bg-light">Editar Perfil</a>
                                <a href="{% url 'auth_password_change' %}" class="list-group-item list-group-item-action bg-light">Modificar Contraseña</a>
                                {% endif %}

                                {% if request.user.Egresado and not user.is_superuser and not user.Administrador %}
                                <a href="{% url 'posts:list' %}" class="list-group-item list-group-item-action bg-light">Ver Noticias</a>
                                <a href="{% url 'users:userupdate' %}" class="list-group-item list-group-item-action bg-light">Editar Perfil</a>
                                <a href="{% url 'auth_password_change' %}" class="list-group-item list-group-item-action bg-light">Modificar Contraseña</a>
                                {% endif %}
                                
                            </div>
                        </div>
                </div>
                <div class="col-sm-8" id="left">
                    <!--All apps -->
                    <div class="panel panel-default" ng-init="">
                        <!-- Default panel contents -->
                        <div class="panel-heading clearfix">
                            <b><h3 class="panel-title"><strong> </strong>
                                Observatorio Egresados UTP
                            </b>
                         </div>
                        <div class="panel-body">
                        <table-here>

Observatorio/Django-env/src/templates/headsidebar2.html
{% load static %}
</table-here>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

Observatorio/Django-env/src/templates/navbar.html
{% load static %}
<!-- Static navbar -->
<nav  class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Observatorio Egresados</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >
        <img src= '{% static "img/logoUTP.png" %}' class="img-responsive" class="d-inline-block align-top" width="100" height="100" >
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'portal:inicio' %}">Inicio</a></li>

        {% if request.user.is_authenticated  %}
            <li><a href="{% url 'users:userdetail' %}">   Ver Perfil</a></li>
        {% endif %}

        {% if request.user.Administrador or request.user.Egresado and not user.is_superuser %}
        <!-- <li><a href="{% url 'users:userlist' %}">   Ver Perfil</a></li> -->
            <li class="active"><a href="{% url 'portal:contact' %}">   Contacto</a></li>
        {% endif %}
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul> -->
        </li>
      </ul>
        <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li class="active"><a href="{% url 'auth_logout' %}">Cerrar Sesion</a></li>
        <!-- <li><a href="{% url 'registration_register' %}">Registrarte</a></li>   -->
        <!-- <li class="active"><a href="{% url 'auth_login' %}">Login</a></li> -->
        {% endif %}
        </ul>

      {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
          <form class="navbar-form navbar-right" method="POST" action="{% url 'auth_login' %}">{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" name="username" placeholder="Usuario"/>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" name="password" placeholder="Clave"/>
            </div>
            <button type="submit" class="btn btn-default">Iniciar Sesion</button>
          </form>
      {% else %}
          {% if not user.is_superuser and request.user.Administrador%}
              <center><h3 style="margin: 12px"><span class="label label-default">Administrador | {{request.user }}</h3></span></center>
          {% endif %}
          {% if  user.is_superuser %} 
              <center><h3 style="margin: 12px"><span class="label label-default">Superusuario | {{request.user }}</h3></span></center>
          {% endif %}
          {% if  user.Egresado %} 
              <center><h3 style="margin: 12px"><span class="label label-default">Usuario | {{request.user }}</h3></span></center>
          {% endif %}
      {% endif %}
    </div><!--/.nav-collapse -->
  </div>
</nav>

Observatorio/Django-env/src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title%}Crear Noticia | {{ block.super }} {% endblock %}

{% block content %}
<div class="col-sm-10 col-sm-offset-1" >
<!-- <h2><center><strong>Crear Noticia</strong> </center></h2> -->
    <form method="POST" action="" enctype="multipart/form-data" >{% csrf_token %}
        {{ form|crispy }}
        <br/>
        <p class="text-center"><input class="btn btn-primary" type="submit" value="Crear Noticia">
        <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a> </p>
    </form>
</div>
{% endblock %}

Observatorio/Django-env/src/templates/user_disable.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title%}Deshabilitar Cuenta | {{ block.super }} {% endblock %}

{% block content %}
<div class="col-sm-10 col-sm-offset-1" >
<!-- <h2><center><strong>Deshabilitar Cuenta</strong> </center></h2> -->
    <form method="POST" action="" enctype="multipart/form-data" >{% csrf_token %}
        <div class="panel panel-info">
            <div class="panel-heading">Nombre de usuario</div>
            <div class="panel-body">
                {{ instance.username }}            
            </div>
          </div>
          <div class="panel panel-info">
            <div class="panel-heading">Dirección de correo electrónico</div>
            <div class="panel-body">
                {{ instance.email }}
            </div>
          </div><div class="panel panel-info">
            <div class="panel-heading">Deshabilitar Usuario</div>
            <div class="panel-body">
                {{ form|crispy }}
            </div>
          </div>
          <br/>
        <p class="text-center">
        <input class="btn btn-primary" type="submit" value="Guardar Cambios">
        <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a></p> 
    </form>
</div>
{% endblock %}

Observatorio/Django-env/src/templates/user_list_update.html
{% extends "base.html" %}
    {% block head_title%}Modificar Usuario | {{ block.super }} {% endblock %}

    {% block content %}
    <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script> -->
    <!------ Include the above in your HEAD tag ---------->
<div class="col-sm-10 col-sm-offset-1">
    <!-- <h2><strong><center>{{ title }}</center></strong></h2> -->
    <center>
    <form method="GET" action="">
        <input class="text-align-center" type="text" name="q" placeholder="Buscar Usuario" value="{{ request.GET.q }}"/>
        <input type="submit" value="Buscar" />
    </form>
    </center>
    <!-- {{ objects_list }} <br/> -->
    <br>

{% if user.is_superuser %}
    {% for obj in objects_list %}
        {% if obj.Administrador %}
                  <div class="col">
                      
                    <div class="panel-body">
                      <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                        {% if not obj.imagen_Perfil %}
                            <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive"> 
                        {% else %}
                            <img src="{{ obj.imagen_Perfil.url }}" class="img-circle img-responsive"/>
                        {% endif %}
                        
                        {% if obj.biografia %}
                        <h4><strong>Biografia</strong></h4> 
                        <p>{{ obj.biografia }}</p>
                        {% endif %}
                 
                      </div>
                      <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8" >
                          <div class="container" >
                            <h2><strong>{{ obj.username }}</strong></h2>
                            <p>Cargo: <b> {% if obj.is_superuser %} Superusuario {% endif %}{% if obj.Administrador %}Administrador {% endif %}</b></p>
                          
                           
                          </div>
                           <hr>
                          <ul class="container details" >
                            <li><p><span class="glyphicon glyphicon-user one" style="width:50px;"></span>{% if obj.get_full_name %}{{ obj.get_full_name }} {% else %}{{ obj.username }} {% endif %}</p></li>
                            <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span>{{ obj.email }}</p></li>
                            {% if obj.telefono %}<li><p><span class="glyphicon glyphicon-phone" style="width:50px;"></span>{{ obj.telefono }}</p></li>{% endif %}
                            {% if obj.ciudad %}<li><p><span class="glyphicon glyphicon-globe" style="width:50px;"></span>{{ obj.ciudad }}</p></li>{% endif %}
                          </ul>
                          <hr>
                          <div class="col-sm-12 col-xs-12 tital " >{% if obj.fecha_Nacimiento %}Fecha de Nacimiento: {{ obj.fecha_Nacimiento }}{% endif %}</div>
                          <hr>
                          <div class="col-sm-12 col-xs-12 tital " >Se unió: {{ obj.date_joined }}</div>
                          
                      </div>
                    </div>
                    <hr>
                    <p class="text-center"><a href="{% url 'users:useradminupdateobservatorio' id=obj.id %}" class="btn btn-primary" role="button">Modificar Datos Administrador</a>
                    <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a> </p>
                </div>
        {% endif %}
    {% endfor %}
{% endif %}

{% if user.Administrador and not user.is_superuser %}
    {% for obj in objects_list %}
        {% if obj.Egresado %}
                  <div class="col">
                      
                    <div class="panel-body">
                      <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                        {% if not obj.imagen_Perfil %}
                            <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive"> 
                        {% else %}
                            <img src="{{ obj.imagen_Perfil.url }}" class="img-circle img-responsive"/>
                        {% endif %}
                        
                        {% if obj.biografia %}
                        <h4><strong>Biografia</strong></h4> 
                        <p>{{ obj.biografia }}</p>
                        {% endif %}
                 
                      </div>
                      <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8" >
                          <div class="container" >
                            <h2><strong>{{ obj.username }}</strong></h2>
                            <p>Cargo: <b> {% if obj.is_superuser %} Superusuario {% endif %}{% if obj.Administrador %}Administrador {% endif %}{% if obj.Egresado %}Usuario {% endif %}</b></p>
                          
                           
                          </div>
                           <hr>
                          <ul class="container details" >
                            <li><p><span class="glyphicon glyphicon-user one" style="width:50px;"></span>{% if obj.get_full_name %}{{ obj.get_full_name }} {% else %}{{ obj.username }} {% endif %}</p></li>
                            <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span>{{ obj.email }}</p></li>
                            {% if obj.telefono %}<li><p><span class="glyphicon glyphicon-phone" style="width:50px;"></span>{{ obj.telefono }}</p></li>{% endif %}
                            {% if obj.ciudad %}<li><p><span class="glyphicon glyphicon-globe" style="width:50px;"></span>{{ obj.ciudad }}</p></li>{% endif %}
                          </ul>
                          <hr>
                          <div class="col-sm-12 col-xs-12 tital " >{% if obj.fecha_Nacimiento %}Fecha de Nacimiento: {{ obj.fecha_Nacimiento }}{% endif %}</div>
                          <hr>
                          <div class="col-sm-12 col-xs-12 tital " >Se unió: {{ obj.date_joined }}</div>
                          
                      </div>
                    </div>
                    <hr>
                    <p class="text-center"><a href="{% url 'users:userupdateobservatorio' id=obj.id %}" class="btn btn-primary" role="button">Modificar Datos Administrador</a>
                    <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a> </p>
                </div>
        {% endif %}
    {% endfor %}
{% endif %}
    <div class="pagination">
        <span class="step-links">
            {% if objects_list.has_previous %}
                <a href="?page=1 {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo; primero</a>
                <a href="?page={{ objects_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">anterior</a>
            {% endif %}
    
            <span class="current">
                Usuario {{ objects_list.number }} de {{ objects_list.paginator.num_pages }}
            </span>
    
            {% if objects_list.has_next %}
                <a href="?page={{ objects_list.next_page_number }} {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">siguiente</a>
                <a href="?page={{ objects_list.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">último &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
    {% endblock %}

    <!-- {% url 'posts:detail' id=obj.id %}  familia  App posts vista detail -->    
    <!-- {{obj.pk}} <br/> -->           
            